import DestinationExplorer from "./DestinationExplorer";
import TravelWiseLogo from "./TravelWiseLogo";
import "./LandingPage.css";

const help = ["Smart Trip Planning", "Budget Management", "Weather-Aware Recommendations", "Transport Planning", "Safety & Readiness", "Return Trip Planning"];
const journey = ["Plan Trip", "Check Route", "Check Weather", "Manage Budget", "Build Itinerary", "Travel", "Reach Destination", "Plan Return", "Complete Trip"];

export default function LandingPage({ onGetStarted, onSignIn, onPlanDestination }) {
  return <main className="landing-page">
    <header className="landing-nav"><a href="#top" aria-label="TravelWise home"><TravelWiseLogo size={34} light showTagline /></a><nav><a href="#destinations">Destinations</a><a href="#how-it-helps">How it helps</a><a href="#journey">Journey</a><button onClick={onSignIn}>Sign In</button><button className="landing-nav-cta" onClick={onGetStarted}>Get Started</button></nav></header>
    <section className="landing-hero" id="top"><div className="landing-hero-copy"><p className="landing-kicker">Travel with intention</p><h1>Go further.<br /><em>Feel closer.</em></h1><p>A calmer way to plan meaningful journeys, with the clarity to enjoy every mile.</p><div className="landing-actions"><button className="landing-primary" onClick={onGetStarted}>Plan Your Trip <span>-&gt;</span></button><a className="landing-ghost" href="#destinations">Explore Destinations <span>↓</span></a></div><small>● Built for the whole journey　|　Local and international trips</small></div><div className="landing-glass"><small>YOUR NEXT ESCAPE</small><strong>Your next journey</strong><span>Made for your pace</span><hr /><small>Weather-aware　 Budget ready　 Return planned</small></div><a className="landing-scroll" href="#destinations">Scroll to explore ↓</a></section>
    <section className="landing-section" id="destinations"><DestinationExplorer onPlan={onPlanDestination || onGetStarted}/></section>
    <section className="landing-section landing-help" id="how-it-helps"><div className="landing-heading"><div><p className="landing-kicker dark">The TravelWise difference</p><h2>Every detail considered.<br /><i>More room to wander.</i></h2></div><p>Practical travel planning in one calm, connected place, so you can focus on being there.</p></div><div className="landing-help-grid">{help.map((item, index) => <article key={item}><small>0{index + 1}</small><h3>{item}</h3><p>{["Build a practical itinerary around your dates, pace, and interests.", "Track daily spend, food allowances, and a protected return reserve.", "Adjust activities and dates when live conditions change.", "Keep routes, transfers, and arrival timing clear.", "Prepare with risk signals, checklists, and packing guidance.", "Plan the way back with the same care as the way there."][index]}</p></article>)}</div></section>
    <section className="landing-journey" id="journey"><div><p className="landing-kicker">One connected journey</p><h2>From first idea<br /><em>to home again.</em></h2><p>Plans change. TravelWise keeps up, with a clear view of every step and confidence in the next one.</p><button className="landing-primary" onClick={onGetStarted}>Begin planning <span>-&gt;</span></button></div><div className="landing-steps">{journey.map((step, index) => <div key={step}><small>{String(index + 1).padStart(2, "0")}</small><strong>{step}</strong>{index < journey.length - 1 && <i>→</i>}</div>)}</div></section>
    <footer><TravelWiseLogo size={28} light /><p>Thoughtful planning for wherever you are going next.</p><div><button onClick={onSignIn}>Sign In</button><button onClick={onGetStarted}>Get Started</button></div></footer>
  </main>;
}
