<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.29" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.8" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="TravelWise.API.Integrations.Geoapify" />
    <Using Include="TravelWise.API.Integrations.OpenMeteo" />
    <Using Include="TravelWise.API.Integrations.AIService" />
    <Using Include="TravelWise.API.DTO" />
    <Using Include="TravelWise.API.DTOs" />
    <Using Include="TravelWise.API.Services.Risk" />
    <Using Include="TravelWise.API.Services.Budget" />
  </ItemGroup>

</Project>
